kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: persistent-volume-claim-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
